//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFacturaMvc.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailMarketing
    {
        public int idMarketing { get; set; }
        public string nombre { get; set; }
        public string email { get; set; }
        public Nullable<int> dias { get; set; }
        public Nullable<System.DateTime> fechaComienzo { get; set; }
        public string idUsuario { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
