//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFacturaMvc.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class envio
    {
        public int idEnvio { get; set; }
        public int idVenta { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string estado { get; set; }
        public string numeroGuia { get; set; }
        public Nullable<int> paqueteria { get; set; }
        public string usuarioEnvio { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual venta venta { get; set; }
        public virtual paqueteria paqueteria1 { get; set; }
    }
}
