//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFacturaMvc.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class factura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public factura()
        {
            this.detalleCotizacion = new HashSet<detalleCotizacion>();
        }
    
        public decimal numFactura { get; set; }
        public System.DateTime fecha { get; set; }
        public float IVA { get; set; }
        public float total { get; set; }
        public int numPago { get; set; }
        public Nullable<decimal> descuento { get; set; }
    
        public virtual modoPago modoPago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalleCotizacion> detalleCotizacion { get; set; }
    }
}
