//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFacturaMvc.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class oportunidad
    {
        public int idOportunidad { get; set; }
        public Nullable<decimal> cotizacion { get; set; }
        public string notas { get; set; }
        public string acciones { get; set; }
        public Nullable<decimal> venta { get; set; }
        public Nullable<decimal> costo { get; set; }
        public string estatus { get; set; }
        public string idUsuario { get; set; }
        public Nullable<int> porcentaje { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual cotizacion cotizacion1 { get; set; }
    }
}
