//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFacturaMvc.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class RFQItem
    {
        public int idRFQItem { get; set; }
        public Nullable<int> idRfq { get; set; }
        public Nullable<int> idProveedor { get; set; }
        public string idProducto { get; set; }
        public Nullable<float> precio { get; set; }
        public Nullable<int> cantidad { get; set; }
        public string notas { get; set; }
    
        public virtual producto producto { get; set; }
        public virtual proveedor proveedor { get; set; }
        public virtual RFQ RFQ { get; set; }
    }
}
