//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFacturaMvc.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class venta
    {
        public int idVenta { get; set; }
        public Nullable<decimal> idCotizacion { get; set; }
        public Nullable<decimal> idCliente { get; set; }
        public string codigoPostal { get; set; }
        public Nullable<int> idCiudad { get; set; }
        public string calle { get; set; }
        public string numeroExt { get; set; }
        public string numeroInt { get; set; }
        public string colonia { get; set; }
        public string telefonoContacto { get; set; }
        public byte[] archivo { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string vendedor { get; set; }
    
        public virtual ciudad ciudad { get; set; }
        public virtual cliente cliente { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
