//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFacturaMvc.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class venta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public venta()
        {
            this.envio = new HashSet<envio>();
            this.ventaDetalle = new HashSet<ventaDetalle>();
        }
    
        public int idVenta { get; set; }
        public Nullable<decimal> idCotizacion { get; set; }
        public Nullable<decimal> idCliente { get; set; }
        public string codigoPostal { get; set; }
        public Nullable<int> idCiudad { get; set; }
        public string calle { get; set; }
        public string numeroExt { get; set; }
        public string numeroInt { get; set; }
        public string colonia { get; set; }
        public string telefonoContacto { get; set; }
        public byte[] archivo { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string vendedor { get; set; }
        public string terminos { get; set; }
    
        public virtual ciudad ciudad { get; set; }
        public virtual cliente cliente { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<envio> envio { get; set; }
        public virtual cotizacion cotizacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ventaDetalle> ventaDetalle { get; set; }
    }
}
